title: SHIVASHISH UPADHYAY
description: "I'm a Computer Science student with experience in Java, Python, SQL, and JavaScript. I’ve mentored students and developed real-world applications, and I’m seeking internship opportunities in machine learning and full stack development.   "
description:  " 662-410-6021 | SAGINAW, USA | GitHub: upadhyayashish853@gmail.com | Email: shivashishupadhyay0@gmail.com"
google_analytics: "<Your-Google-Analytics-ID>"
theme: jekyll-theme-cayman

