title: SHIVASHISH UPADHYAY
description: "I’m Shivashish Upadhyay, a Computer Science student with experience in Java, Python, SQL, and JavaScript.
 I’ve mentored students and developed real-world applications,and I’m seeking internship opportunities in machine learning 
and full stack development."
662-410-6021 | SAGINAW, USA |  GitHub:upadhyayashish853@gmail.com     Email: shivashishupadhyay0@gmail.com  
google_analytics:
theme: jekyll-theme-cayman
