title: SHIVASHISH UPADHYAY
description: "I'm a Computer Science student with experience in Java, Python, SQL, and JavaScript. I’ve mentored students and developed real-world applications, and I’m seeking internship opportunities in machine learning and full stack development. 662-410-6021 | SAGINAW, USA | GitHub: upadhyayashish853@gmail.com | Email: shivashishupadhyay0@gmail.com"
google_analytics: "<Your-Google-Analytics-ID>"
theme: jekyll-theme-cayman
header_image: "https://github.com/supadhy1-tech/supadhy1.github.io/blob/main/headshot.jpg?raw=true"
